#************************************************************/
#*    NAME: 	Supun Randeni
#*    E-MAIL:	supun@mit.edu                                           
#*    ORGN: 	Dept of Mechanical Engineering, MIT, Cambridge MA                                            
#*    FILE: 	SeaScanner/src/moos/CMakeLists.txt                                     
#*    DATE: 	2024-
#*    INFO:                                         
#************************************************************/

#============================================================================
# List the subdirectories to build...
#============================================================================

# MOOS Apps
#ADD_SUBDIRECTORY(xxxx)


##############################################################################
#                           END of CMakeLists.txt
##############################################################################

